/**
 * HSN/SAC master for invoice lines: merges API GST config, inventory items, and a built-in reference.
 * Full official HSN runs to 10000+ lines — maintain extras under GST → Configurations in the app.
 */

export const COMMON_HSN_REFERENCE = [
  { hsnCode: '0401', gstRate: 5, description: 'Milk and cream' },
  { hsnCode: '0402', gstRate: 5, description: 'Milk products (curd, etc.)' },
  { hsnCode: '0403', gstRate: 5, description: 'Buttermilk, yogurt, whey' },
  { hsnCode: '0406', gstRate: 5, description: 'Cheese and curd' },
  { hsnCode: '0701', gstRate: 0, description: 'Potatoes, fresh' },
  { hsnCode: '0702', gstRate: 5, description: 'Tomatoes, fresh' },
  { hsnCode: '0703', gstRate: 5, description: 'Onions, shallots, garlic' },
  { hsnCode: '0713', gstRate: 5, description: 'Dried leguminous vegetables' },
  { hsnCode: '0803', gstRate: 0, description: 'Bananas' },
  { hsnCode: '0804', gstRate: 5, description: 'Dates, figs, avocados' },
  { hsnCode: '0805', gstRate: 0, description: 'Citrus fruit' },
  { hsnCode: '0901', gstRate: 5, description: 'Coffee' },
  { hsnCode: '0902', gstRate: 5, description: 'Tea' },
  { hsnCode: '0904', gstRate: 5, description: 'Pepper, spices' },
  { hsnCode: '1001', gstRate: 0, description: 'Wheat and meslin' },
  { hsnCode: '1006', gstRate: 0, description: 'Rice' },
  { hsnCode: '1101', gstRate: 0, description: 'Wheat flour (atta)' },
  { hsnCode: '1102', gstRate: 5, description: 'Cereal flours' },
  { hsnCode: '1507', gstRate: 5, description: 'Soya-bean oil' },
  { hsnCode: '1517', gstRate: 5, description: 'Margarine, edible mixtures' },
  { hsnCode: '1701', gstRate: 5, description: 'Sugar' },
  { hsnCode: '1704', gstRate: 18, description: 'Sugar confectionery' },
  { hsnCode: '1806', gstRate: 18, description: 'Chocolate and cocoa prep' },
  { hsnCode: '1901', gstRate: 18, description: 'Malt extract, food prep' },
  { hsnCode: '1902', gstRate: 18, description: 'Pasta, noodles' },
  { hsnCode: '1905', gstRate: 18, description: 'Bread, bakery' },
  { hsnCode: '2005', gstRate: 12, description: 'Vegetables prepared/preserved' },
  { hsnCode: '2009', gstRate: 12, description: 'Fruit juices' },
  { hsnCode: '2106', gstRate: 18, description: 'Food preparations NEC' },
  { hsnCode: '2201', gstRate: 18, description: 'Water (packaged)' },
  { hsnCode: '2202', gstRate: 28, description: 'Aerated drinks (+cess)' },
  { hsnCode: '2203', gstRate: 18, description: 'Beer' },
  { hsnCode: '2204', gstRate: 18, description: 'Wine' },
  { hsnCode: '2402', gstRate: 28, description: 'Cigarettes (+cess)' },
  { hsnCode: '2404', gstRate: 28, description: 'Other tobacco (+cess)' },
  { hsnCode: '2501', gstRate: 5, description: 'Salt' },
  { hsnCode: '2523', gstRate: 28, description: 'Cement (+cess)' },
  { hsnCode: '2710', gstRate: 18, description: 'Petroleum oils (excl bulk)' },
  { hsnCode: '2711', gstRate: 18, description: 'LPG, hydrocarbons' },
  { hsnCode: '3004', gstRate: 12, description: 'Medicaments (formulated)' },
  { hsnCode: '3006', gstRate: 12, description: 'Surgical, pharma goods' },
  { hsnCode: '3303', gstRate: 18, description: 'Perfumes, toilet waters' },
  { hsnCode: '3304', gstRate: 18, description: 'Beauty / make-up' },
  { hsnCode: '3305', gstRate: 18, description: 'Hair preparations' },
  { hsnCode: '3401', gstRate: 18, description: 'Soap, organic surface-active' },
  { hsnCode: '3402', gstRate: 18, description: 'Detergents' },
  { hsnCode: '3506', gstRate: 18, description: 'Glues, adhesives' },
  { hsnCode: '3917', gstRate: 18, description: 'Plastic tubes, pipes' },
  { hsnCode: '3918', gstRate: 18, description: 'Plastic fittings' },
  { hsnCode: '3919', gstRate: 18, description: 'Plastic plates, film' },
  { hsnCode: '3920', gstRate: 18, description: 'Plastic sheets' },
  { hsnCode: '3921', gstRate: 18, description: 'Plastic plates/sheets finished' },
  { hsnCode: '3922', gstRate: 18, description: 'Plastic baths, sanitary' },
  { hsnCode: '3923', gstRate: 18, description: 'Plastic articles for conveyance' },
  { hsnCode: '3924', gstRate: 18, description: 'Tableware, kitchen plastic' },
  { hsnCode: '3925', gstRate: 18, description: 'Builders ware of plastic' },
  { hsnCode: '3926', gstRate: 18, description: 'Other plastic articles' },
  { hsnCode: '4010', gstRate: 18, description: 'Conveyor belts, rubber' },
  { hsnCode: '4011', gstRate: 28, description: 'New pneumatic tyres' },
  { hsnCode: '4012', gstRate: 18, description: 'Retreaded tyres' },
  { hsnCode: '4013', gstRate: 18, description: 'Inner tubes' },
  { hsnCode: '4014', gstRate: 12, description: 'Hygiene / pharma rubber' },
  { hsnCode: '4015', gstRate: 18, description: 'Apparel of rubber' },
  { hsnCode: '4016', gstRate: 18, description: 'Other rubber articles' },
  { hsnCode: '4202', gstRate: 18, description: 'Trunks, bags, handbags' },
  { hsnCode: '4303', gstRate: 5, description: 'Articles of fur' },
  { hsnCode: '4407', gstRate: 5, description: 'Wood sawn/chipped' },
  { hsnCode: '4410', gstRate: 12, description: 'Particle board, OSB' },
  { hsnCode: '4412', gstRate: 18, description: 'Plywood, veneered panels' },
  { hsnCode: '4418', gstRate: 18, description: 'Builders joinery of wood' },
  { hsnCode: '4419', gstRate: 12, description: 'Tableware of wood' },
  { hsnCode: '4420', gstRate: 12, description: 'Wood marquetry, statuettes' },
  { hsnCode: '4421', gstRate: 18, description: 'Other articles of wood' },
  { hsnCode: '4819', gstRate: 12, description: 'Cartons, boxes of paper' },
  { hsnCode: '4820', gstRate: 12, description: 'Registers, notebooks' },
  { hsnCode: '4821', gstRate: 12, description: 'Paper labels' },
  { hsnCode: '4823', gstRate: 12, description: 'Paper cut to shape' },
  { hsnCode: '4901', gstRate: 12, description: 'Printed books' },
  { hsnCode: '4902', gstRate: 12, description: 'Newspapers, journals' },
  { hsnCode: '4911', gstRate: 12, description: 'Other printed matter' },
  { hsnCode: '6103', gstRate: 5, description: 'Knitted suits, men/boys' },
  { hsnCode: '6104', gstRate: 5, description: 'Knitted suits, women' },
  { hsnCode: '6105', gstRate: 5, description: 'Knitted shirts' },
  { hsnCode: '6106', gstRate: 5, description: 'Knitted blouses' },
  { hsnCode: '6107', gstRate: 5, description: 'Knitted undergarments men' },
  { hsnCode: '6108', gstRate: 5, description: 'Knitted undergarments women' },
  { hsnCode: '6109', gstRate: 5, description: 'T-shirts, vests knitted' },
  { hsnCode: '6110', gstRate: 5, description: 'Jerseys, pullovers' },
  { hsnCode: '6111', gstRate: 5, description: 'Babies garments knitted' },
  { hsnCode: '6112', gstRate: 5, description: 'Track suits knitted' },
  { hsnCode: '6113', gstRate: 5, description: 'Garments rubber/plastic coated' },
  { hsnCode: '6114', gstRate: 5, description: 'Other knitted garments' },
  { hsnCode: '6115', gstRate: 5, description: 'Hosiery' },
  { hsnCode: '6116', gstRate: 5, description: 'Gloves, mittens knitted' },
  { hsnCode: '6117', gstRate: 5, description: 'Made-up clothing accessories' },
  { hsnCode: '6203', gstRate: 5, description: 'Men suits not knitted' },
  { hsnCode: '6204', gstRate: 5, description: 'Women suits not knitted' },
  { hsnCode: '6205', gstRate: 5, description: 'Men shirts not knitted' },
  { hsnCode: '6206', gstRate: 5, description: 'Women blouses' },
  { hsnCode: '6301', gstRate: 5, description: 'Blankets' },
  { hsnCode: '6302', gstRate: 5, description: 'Bed linen' },
  { hsnCode: '6303', gstRate: 5, description: 'Curtains' },
  { hsnCode: '6304', gstRate: 5, description: 'Other furnishing articles' },
  { hsnCode: '6305', gstRate: 5, description: 'Sacks bags for packing' },
  { hsnCode: '6306', gstRate: 5, description: 'Tarpaulins, tents' },
  { hsnCode: '6307', gstRate: 5, description: 'Other made-up textiles' },
  { hsnCode: '6308', gstRate: 5, description: 'Sets of woven fabric' },
  { hsnCode: '6309', gstRate: 5, description: 'Worn clothing' },
  { hsnCode: '6310', gstRate: 5, description: 'Used rags' },
  { hsnCode: '6401', gstRate: 18, description: 'Waterproof footwear' },
  { hsnCode: '6402', gstRate: 18, description: 'Rubber/plastic footwear' },
  { hsnCode: '6403', gstRate: 18, description: 'Leather footwear' },
  { hsnCode: '6404', gstRate: 18, description: 'Textile footwear' },
  { hsnCode: '6405', gstRate: 18, description: 'Other footwear' },
  { hsnCode: '6505', gstRate: 5, description: 'Hats and headgear' },
  { hsnCode: '6810', gstRate: 28, description: 'Articles of cement (+cess)' },
  { hsnCode: '6907', gstRate: 28, description: 'Ceramic flags, tiles (+cess)' },
  { hsnCode: '6912', gstRate: 18, description: 'Ceramic tableware' },
  { hsnCode: '7005', gstRate: 18, description: 'Float glass' },
  { hsnCode: '7009', gstRate: 18, description: 'Glass mirrors' },
  { hsnCode: '7010', gstRate: 18, description: 'Glass ampoules, containers' },
  { hsnCode: '7013', gstRate: 18, description: 'Glassware for table/kitchen' },
  { hsnCode: '7018', gstRate: 18, description: 'Glass beads, imitation jewellery' },
  { hsnCode: '7108', gstRate: 3, description: 'Gold (precious metal)' },
  { hsnCode: '7113', gstRate: 3, description: 'Articles of jewellery' },
  { hsnCode: '7117', gstRate: 3, description: 'Imitation jewellery' },
  { hsnCode: '7208', gstRate: 18, description: 'Flat-rolled iron/steel' },
  { hsnCode: '7210', gstRate: 18, description: 'Plated/coated flat steel' },
  { hsnCode: '7213', gstRate: 18, description: 'Bars and rods iron' },
  { hsnCode: '7218', gstRate: 18, description: 'Stainless steel' },
  { hsnCode: '7219', gstRate: 18, description: 'Flat-rolled stainless' },
  { hsnCode: '7220', gstRate: 18, description: 'Narrow stainless strip' },
  { hsnCode: '7222', gstRate: 18, description: 'Other bars stainless' },
  { hsnCode: '7223', gstRate: 18, description: 'Wire of stainless steel' },
  { hsnCode: '7301', gstRate: 18, description: 'Sheet piling' },
  { hsnCode: '7302', gstRate: 18, description: 'Railway track material' },
  { hsnCode: '7303', gstRate: 18, description: 'Tubes, pipes cast iron' },
  { hsnCode: '7304', gstRate: 18, description: 'Tubes, pipes seamless steel' },
  { hsnCode: '7305', gstRate: 18, description: 'Tubes, pipes welded 215mm+' },
  { hsnCode: '7306', gstRate: 18, description: 'Other tubes, pipes steel' },
  { hsnCode: '7307', gstRate: 18, description: 'Tube/pipe fittings' },
  { hsnCode: '7308', gstRate: 18, description: 'Structures, parts of iron/steel' },
  { hsnCode: '7309', gstRate: 18, description: 'Tanks, vats 300l+' },
  { hsnCode: '7310', gstRate: 18, description: 'Tanks, drums <300l' },
  { hsnCode: '7311', gstRate: 18, description: 'LPG containers' },
  { hsnCode: '7312', gstRate: 18, description: 'Stranded wire, ropes' },
  { hsnCode: '7313', gstRate: 18, description: 'Barbed wire' },
  { hsnCode: '7314', gstRate: 18, description: 'Cloth, grill of iron wire' },
  { hsnCode: '7315', gstRate: 18, description: 'Chain and parts' },
  { hsnCode: '7316', gstRate: 18, description: 'Anchors, grapnels' },
  { hsnCode: '7317', gstRate: 18, description: 'Nails, staples' },
  { hsnCode: '7318', gstRate: 18, description: 'Screws, bolts, nuts' },
  { hsnCode: '7319', gstRate: 18, description: 'Sewing needles, pins' },
  { hsnCode: '7320', gstRate: 18, description: 'Springs of iron/steel' },
  { hsnCode: '7321', gstRate: 18, description: 'Stoves, ranges, non-electric' },
  { hsnCode: '7322', gstRate: 18, description: 'Radiators, air heaters' },
  { hsnCode: '7323', gstRate: 18, description: 'Table, kitchen, other household steel' },
  { hsnCode: '7324', gstRate: 18, description: 'Sanitary ware steel' },
  { hsnCode: '7325', gstRate: 18, description: 'Other cast articles iron/steel' },
  { hsnCode: '7326', gstRate: 18, description: 'Other articles iron/steel' },
  { hsnCode: '7418', gstRate: 18, description: 'Table, kitchen copper' },
  { hsnCode: '7419', gstRate: 18, description: 'Other articles copper' },
  { hsnCode: '7615', gstRate: 18, description: 'Table, kitchen aluminium' },
  { hsnCode: '7616', gstRate: 18, description: 'Other articles aluminium' },
  { hsnCode: '8201', gstRate: 18, description: 'Hand tools' },
  { hsnCode: '8205', gstRate: 18, description: 'Hand tools misc' },
  { hsnCode: '8207', gstRate: 18, description: 'Interchangeable tools' },
  { hsnCode: '8211', gstRate: 18, description: 'Knives, blades' },
  { hsnCode: '8212', gstRate: 18, description: 'Razors' },
  { hsnCode: '8213', gstRate: 18, description: 'Scissors' },
  { hsnCode: '8214', gstRate: 18, description: 'Other cutlery' },
  { hsnCode: '8215', gstRate: 18, description: 'Spoons, forks' },
  { hsnCode: '8301', gstRate: 18, description: 'Padlocks, locks' },
  { hsnCode: '8302', gstRate: 18, description: 'Mountings, fittings' },
  { hsnCode: '8303', gstRate: 18, description: 'Safes, strongboxes' },
  { hsnCode: '8304', gstRate: 18, description: 'Filing cabinets' },
  { hsnCode: '8305', gstRate: 18, description: 'Loose-leaf binders' },
  { hsnCode: '8306', gstRate: 18, description: 'Bells, ornaments metal' },
  { hsnCode: '8307', gstRate: 18, description: 'Flexible tubing metal' },
  { hsnCode: '8308', gstRate: 18, description: 'Clasps, buckles' },
  { hsnCode: '8309', gstRate: 18, description: 'Stoppers, caps' },
  { hsnCode: '8310', gstRate: 18, description: 'Sign plates' },
  { hsnCode: '8311', gstRate: 18, description: 'Wire for welding' },
  { hsnCode: '8407', gstRate: 28, description: 'Aircraft engines (+cess)' },
  { hsnCode: '8408', gstRate: 28, description: 'Compression-ignition engines' },
  { hsnCode: '8409', gstRate: 28, description: 'Parts for engines' },
  { hsnCode: '8413', gstRate: 18, description: 'Pumps for liquids' },
  { hsnCode: '8414', gstRate: 18, description: 'Fans, air pumps' },
  { hsnCode: '8415', gstRate: 18, description: 'Air conditioning' },
  { hsnCode: '8418', gstRate: 18, description: 'Refrigerators, freezers' },
  { hsnCode: '8419', gstRate: 18, description: 'Industrial heating/cooling' },
  { hsnCode: '8421', gstRate: 18, description: 'Filters, centrifuges' },
  { hsnCode: '8422', gstRate: 18, description: 'Dish washing machines' },
  { hsnCode: '8423', gstRate: 18, description: 'Weighing machinery' },
  { hsnCode: '8424', gstRate: 18, description: 'Spraying appliances' },
  { hsnCode: '8425', gstRate: 18, description: 'Pulley tackle, hoists' },
  { hsnCode: '8426', gstRate: 18, description: 'Cranes' },
  { hsnCode: '8427', gstRate: 18, description: 'Fork-lift trucks' },
  { hsnCode: '8428', gstRate: 18, description: 'Lifts, escalators' },
  { hsnCode: '8429', gstRate: 28, description: 'Bulldozers, excavators' },
  { hsnCode: '8430', gstRate: 18, description: 'Other moving machinery' },
  { hsnCode: '8431', gstRate: 18, description: 'Parts for 8425-8430' },
  { hsnCode: '8432', gstRate: 12, description: 'Agricultural machinery' },
  { hsnCode: '8433', gstRate: 12, description: 'Harvesting machinery' },
  { hsnCode: '8434', gstRate: 12, description: 'Milking machines' },
  { hsnCode: '8435', gstRate: 12, description: 'Presses for wine/cider' },
  { hsnCode: '8436', gstRate: 12, description: 'Agri equipment' },
  { hsnCode: '8437', gstRate: 12, description: 'Seed processing' },
  { hsnCode: '8438', gstRate: 18, description: 'Food industry machinery' },
  { hsnCode: '8439', gstRate: 18, description: 'Paper pulp machinery' },
  { hsnCode: '8440', gstRate: 18, description: 'Bookbinding machinery' },
  { hsnCode: '8441', gstRate: 18, description: 'Paper cutting' },
  { hsnCode: '8442', gstRate: 18, description: 'Print machinery' },
  { hsnCode: '8443', gstRate: 18, description: 'Printing machinery' },
  { hsnCode: '8444', gstRate: 18, description: 'Knitting machines' },
  { hsnCode: '8445', gstRate: 18, description: 'Weaving machines' },
  { hsnCode: '8446', gstRate: 18, description: 'Weaving loom' },
  { hsnCode: '8447', gstRate: 18, description: 'Knitting, stitch machines' },
  { hsnCode: '8448', gstRate: 18, description: 'Auxiliary textile machines' },
  { hsnCode: '8449', gstRate: 18, description: 'Machines for felt' },
  { hsnCode: '8450', gstRate: 18, description: 'Washing machines household' },
  { hsnCode: '8451', gstRate: 18, description: 'Dry-cleaning machines' },
  { hsnCode: '8452', gstRate: 18, description: 'Sewing machines' },
  { hsnCode: '8453', gstRate: 18, description: 'Leather machinery' },
  { hsnCode: '8454', gstRate: 18, description: 'Converters, ladles' },
  { hsnCode: '8455', gstRate: 18, description: 'Metal rolling mills' },
  { hsnCode: '8456', gstRate: 18, description: 'Machine tools laser' },
  { hsnCode: '8457', gstRate: 18, description: 'Machining centres' },
  { hsnCode: '8458', gstRate: 18, description: 'Lathes' },
  { hsnCode: '8459', gstRate: 18, description: 'Boring, milling machines' },
  { hsnCode: '8460', gstRate: 18, description: 'Finishing metal machines' },
  { hsnCode: '8461', gstRate: 18, description: 'Shaping, slotting' },
  { hsnCode: '8462', gstRate: 18, description: 'Forging machines' },
  { hsnCode: '8463', gstRate: 18, description: 'Other machine tools' },
  { hsnCode: '8464', gstRate: 18, description: 'Stone working machines' },
  { hsnCode: '8465', gstRate: 18, description: 'Wood working machines' },
  { hsnCode: '8466', gstRate: 18, description: 'Parts for 8456-8465' },
  { hsnCode: '8467', gstRate: 18, description: 'Hand-held power tools' },
  { hsnCode: '8468', gstRate: 18, description: 'Soldering, welding machines' },
  { hsnCode: '8470', gstRate: 18, description: 'Calculators, cash registers' },
  { hsnCode: '8471', gstRate: 18, description: 'Computers, laptops' },
  { hsnCode: '8472', gstRate: 18, description: 'Office machines NEC' },
  { hsnCode: '8473', gstRate: 18, description: 'Parts for 8470-8472' },
  { hsnCode: '8479', gstRate: 18, description: 'Machines with individual functions' },
  { hsnCode: '8480', gstRate: 18, description: 'Moulding boxes' },
  { hsnCode: '8481', gstRate: 18, description: 'Taps, cocks, valves' },
  { hsnCode: '8482', gstRate: 18, description: 'Ball bearings' },
  { hsnCode: '8483', gstRate: 18, description: 'Transmission shafts' },
  { hsnCode: '8484', gstRate: 18, description: 'Gaskets' },
  { hsnCode: '8485', gstRate: 18, description: 'Machine parts moulded' },
  { hsnCode: '8486', gstRate: 18, description: 'Semiconductor manufacturing' },
  { hsnCode: '8504', gstRate: 18, description: 'Electrical transformers' },
  { hsnCode: '8505', gstRate: 18, description: 'Electro-magnets' },
  { hsnCode: '8506', gstRate: 28, description: 'Primary cells, batteries' },
  { hsnCode: '8507', gstRate: 18, description: 'Electric accumulators' },
  { hsnCode: '8508', gstRate: 18, description: 'Vacuum cleaners' },
  { hsnCode: '8509', gstRate: 18, description: 'Electro-mechanical domestic' },
  { hsnCode: '8510', gstRate: 18, description: 'Shavers, hair clippers' },
  { hsnCode: '8511', gstRate: 28, description: 'Ignition equipment auto' },
  { hsnCode: '8512', gstRate: 28, description: 'Lighting for vehicles' },
  { hsnCode: '8513', gstRate: 18, description: 'Portable electric lamps' },
  { hsnCode: '8514', gstRate: 18, description: 'Industrial furnaces' },
  { hsnCode: '8515', gstRate: 18, description: 'Electric soldering' },
  { hsnCode: '8516', gstRate: 18, description: 'Electric heating appliances' },
  { hsnCode: '8517', gstRate: 18, description: 'Telephone, smartphones' },
  { hsnCode: '8518', gstRate: 18, description: 'Microphones, loudspeakers' },
  { hsnCode: '8519', gstRate: 18, description: 'Sound recording players' },
  { hsnCode: '8521', gstRate: 18, description: 'Video recording' },
  { hsnCode: '8523', gstRate: 18, description: 'Discs, tapes, media' },
  { hsnCode: '8524', gstRate: 18, description: 'Flat panel displays' },
  { hsnCode: '8525', gstRate: 18, description: 'Transmission apparatus' },
  { hsnCode: '8526', gstRate: 18, description: 'Radar, radio navigational' },
  { hsnCode: '8527', gstRate: 18, description: 'Radio receivers' },
  { hsnCode: '8528', gstRate: 28, description: 'Monitors, televisions (+cess)' },
  { hsnCode: '8529', gstRate: 18, description: 'Parts for 8525-8528' },
  { hsnCode: '8530', gstRate: 18, description: 'Electrical signalling' },
  { hsnCode: '8531', gstRate: 18, description: 'Electric sound/visual signalling' },
  { hsnCode: '8532', gstRate: 18, description: 'Capacitors' },
  { hsnCode: '8533', gstRate: 18, description: 'Electrical resistors' },
  { hsnCode: '8534', gstRate: 18, description: 'Printed circuits' },
  { hsnCode: '8535', gstRate: 18, description: 'Switchgear >1kV' },
  { hsnCode: '8536', gstRate: 18, description: 'Electrical apparatus <1kV' },
  { hsnCode: '8537', gstRate: 18, description: 'Control panels' },
  { hsnCode: '8538', gstRate: 18, description: 'Parts for 8535-8537' },
  { hsnCode: '8539', gstRate: 18, description: 'LED lamps, tubes' },
  { hsnCode: '8540', gstRate: 18, description: 'Thermionic tubes' },
  { hsnCode: '8541', gstRate: 18, description: 'Semiconductor devices' },
  { hsnCode: '8542', gstRate: 18, description: 'Electronic integrated circuits' },
  { hsnCode: '8543', gstRate: 18, description: 'Electrical machines NEC' },
  { hsnCode: '8544', gstRate: 18, description: 'Insulated wire, cable' },
  { hsnCode: '8545', gstRate: 18, description: 'Carbon electrodes' },
  { hsnCode: '8546', gstRate: 18, description: 'Electrical insulators' },
  { hsnCode: '8547', gstRate: 18, description: 'Insulating fittings' },
  { hsnCode: '8548', gstRate: 18, description: 'Electrical parts waste' },
  { hsnCode: '8601', gstRate: 5, description: 'Rail locomotives' },
  { hsnCode: '8602', gstRate: 5, description: 'Rail locomotives diesel' },
  { hsnCode: '8603', gstRate: 5, description: 'Self-propelled rail coaches' },
  { hsnCode: '8604', gstRate: 5, description: 'Railway maintenance' },
  { hsnCode: '8605', gstRate: 5, description: 'Railway coaches not self-propelled' },
  { hsnCode: '8606', gstRate: 5, description: 'Railway goods vans' },
  { hsnCode: '8607', gstRate: 5, description: 'Parts of railway' },
  { hsnCode: '8608', gstRate: 5, description: 'Railway fixtures' },
  { hsnCode: '8609', gstRate: 5, description: 'Containers rail/road' },
  { hsnCode: '8701', gstRate: 28, description: 'Tractors (+cess)' },
  { hsnCode: '8702', gstRate: 28, description: 'Buses (+cess)' },
  { hsnCode: '8703', gstRate: 28, description: 'Motor cars (+cess)' },
  { hsnCode: '8704', gstRate: 28, description: 'Motor vehicles goods (+cess)' },
  { hsnCode: '8705', gstRate: 28, description: 'Special purpose motor (+cess)' },
  { hsnCode: '8706', gstRate: 28, description: 'Chassis with engine' },
  { hsnCode: '8707', gstRate: 28, description: 'Bodies for motor vehicles' },
  { hsnCode: '8708', gstRate: 28, description: 'Parts for 8701-8705' },
  { hsnCode: '8709', gstRate: 18, description: 'Works trucks' },
  { hsnCode: '8710', gstRate: 28, description: 'Tanks, armoured (+cess)' },
  { hsnCode: '8711', gstRate: 28, description: 'Motorcycles (+cess)' },
  { hsnCode: '8712', gstRate: 12, description: 'Bicycles' },
  { hsnCode: '8713', gstRate: 5, description: 'Invalid carriages' },
  { hsnCode: '8714', gstRate: 28, description: 'Parts for cycles' },
  { hsnCode: '8715', gstRate: 18, description: 'Baby carriages' },
  { hsnCode: '8716', gstRate: 18, description: 'Trailers, semi-trailers' },
  { hsnCode: '8801', gstRate: 5, description: 'Balloons, dirigibles' },
  { hsnCode: '8802', gstRate: 5, description: 'Aircraft (+cess)' },
  { hsnCode: '8804', gstRate: 5, description: 'Parachutes' },
  { hsnCode: '8805', gstRate: 5, description: 'Aircraft launching' },
  { hsnCode: '8806', gstRate: 5, description: 'Parts of aircraft' },
  { hsnCode: '8807', gstRate: 5, description: 'Parts of 8801-8803' },
  { hsnCode: '8901', gstRate: 5, description: 'Cruise ships, ferries' },
  { hsnCode: '8902', gstRate: 5, description: 'Fishing vessels' },
  { hsnCode: '8903', gstRate: 18, description: 'Yachts, boats pleasure' },
  { hsnCode: '8904', gstRate: 5, description: 'Tugs, pusher craft' },
  { hsnCode: '8905', gstRate: 5, description: 'Light-vessels' },
  { hsnCode: '8906', gstRate: 5, description: 'Other vessels' },
  { hsnCode: '8907', gstRate: 5, description: 'Floating structures' },
  { hsnCode: '8908', gstRate: 5, description: 'Vessels scrap' },
  { hsnCode: '9001', gstRate: 12, description: 'Optical fibres' },
  { hsnCode: '9002', gstRate: 12, description: 'Optical elements mounted' },
  { hsnCode: '9003', gstRate: 12, description: 'Frames for spectacles' },
  { hsnCode: '9004', gstRate: 12, description: 'Spectacles, goggles' },
  { hsnCode: '9005', gstRate: 18, description: 'Binoculars, telescopes' },
  { hsnCode: '9006', gstRate: 18, description: 'Cameras photographic' },
  { hsnCode: '9007', gstRate: 18, description: 'Cinematographic cameras' },
  { hsnCode: '9008', gstRate: 18, description: 'Image projectors' },
  { hsnCode: '9010', gstRate: 18, description: 'Photo labs apparatus' },
  { hsnCode: '9011', gstRate: 12, description: 'Microscopes optical' },
  { hsnCode: '9013', gstRate: 18, description: 'Lasers other than laser diodes' },
  { hsnCode: '9014', gstRate: 12, description: 'Compasses, navigational' },
  { hsnCode: '9015', gstRate: 18, description: 'Surveying instruments' },
  { hsnCode: '9016', gstRate: 18, description: 'Balances sensitive' },
  { hsnCode: '9017', gstRate: 18, description: 'Drawing instruments' },
  { hsnCode: '9018', gstRate: 12, description: 'Medical, surgical instruments' },
  { hsnCode: '9019', gstRate: 12, description: 'Mechano-therapy appliances' },
  { hsnCode: '9020', gstRate: 12, description: 'Breathing appliances' },
  { hsnCode: '9021', gstRate: 12, description: 'Orthopaedic appliances' },
  { hsnCode: '9022', gstRate: 12, description: 'X-ray apparatus' },
  { hsnCode: '9023', gstRate: 18, description: 'Instruments for physical analysis' },
  { hsnCode: '9024', gstRate: 18, description: 'Machines for testing hardness' },
  { hsnCode: '9025', gstRate: 18, description: 'Hydrometers, thermometers' },
  { hsnCode: '9026', gstRate: 18, description: 'Flow, level, pressure meters' },
  { hsnCode: '9027', gstRate: 18, description: 'Gas, smoke analysis' },
  { hsnCode: '9028', gstRate: 18, description: 'Gas, liquid, electricity meters' },
  { hsnCode: '9029', gstRate: 18, description: 'Revolution counters' },
  { hsnCode: '9030', gstRate: 18, description: 'Oscilloscopes' },
  { hsnCode: '9031', gstRate: 18, description: 'Measuring instruments NEC' },
  { hsnCode: '9032', gstRate: 18, description: 'Automatic regulating instruments' },
  { hsnCode: '9033', gstRate: 18, description: 'Parts for 9029-9032' },
  { hsnCode: '9101', gstRate: 18, description: 'Wrist-watches precious metal' },
  { hsnCode: '9102', gstRate: 18, description: 'Wrist-watches other' },
  { hsnCode: '9103', gstRate: 18, description: 'Clocks electric' },
  { hsnCode: '9104', gstRate: 18, description: 'Instrument panel clocks' },
  { hsnCode: '9105', gstRate: 18, description: 'Other clocks' },
  { hsnCode: '9106', gstRate: 18, description: 'Time registers' },
  { hsnCode: '9107', gstRate: 18, description: 'Time switches' },
  { hsnCode: '9108', gstRate: 18, description: 'Watch movements' },
  { hsnCode: '9109', gstRate: 18, description: 'Complete watch movements' },
  { hsnCode: '9110', gstRate: 18, description: 'Incomplete watch movements' },
  { hsnCode: '9111', gstRate: 18, description: 'Watch cases' },
  { hsnCode: '9112', gstRate: 18, description: 'Clock/watch cases' },
  { hsnCode: '9113', gstRate: 18, description: 'Watch straps' },
  { hsnCode: '9114', gstRate: 18, description: 'Other clock parts' },
  { hsnCode: '9201', gstRate: 18, description: 'Pianos' },
  { hsnCode: '9202', gstRate: 18, description: 'String musical instruments' },
  { hsnCode: '9205', gstRate: 18, description: 'Wind musical instruments' },
  { hsnCode: '9206', gstRate: 18, description: 'Percussion instruments' },
  { hsnCode: '9207', gstRate: 18, description: 'Keyboard instruments electric' },
  { hsnCode: '9208', gstRate: 18, description: 'Musical boxes' },
  { hsnCode: '9209', gstRate: 18, description: 'Parts of musical instruments' },
  { hsnCode: '9301', gstRate: 28, description: 'Military arms (+cess)' },
  { hsnCode: '9302', gstRate: 28, description: 'Revolvers, pistols' },
  { hsnCode: '9303', gstRate: 28, description: 'Other firearms' },
  { hsnCode: '9304', gstRate: 18, description: 'Spring, air guns' },
  { hsnCode: '9305', gstRate: 18, description: 'Parts of arms' },
  { hsnCode: '9306', gstRate: 18, description: 'Bombs, grenades' },
  { hsnCode: '9307', gstRate: 18, description: 'Swords, blades' },
  { hsnCode: '9401', gstRate: 18, description: 'Seats' },
  { hsnCode: '9402', gstRate: 18, description: 'Medical, surgical furniture' },
  { hsnCode: '9403', gstRate: 18, description: 'Other furniture' },
  { hsnCode: '9404', gstRate: 12, description: 'Mattress supports' },
  { hsnCode: '9405', gstRate: 18, description: 'Lamps, lighting fittings' },
  { hsnCode: '9406', gstRate: 18, description: 'Prefabricated buildings' },
  { hsnCode: '9503', gstRate: 12, description: 'Toys, models' },
  { hsnCode: '9504', gstRate: 28, description: 'Video game consoles' },
  { hsnCode: '9505', gstRate: 18, description: 'Festive articles' },
  { hsnCode: '9506', gstRate: 12, description: 'Sports equipment' },
  { hsnCode: '9507', gstRate: 12, description: 'Fishing tackle' },
  { hsnCode: '9508', gstRate: 18, description: 'Roundabouts, fairground' },
  { hsnCode: '9601', gstRate: 18, description: 'Worked ivory, bone' },
  { hsnCode: '9602', gstRate: 18, description: 'Vegetable carving' },
  { hsnCode: '9603', gstRate: 18, description: 'Brooms, brushes' },
  { hsnCode: '9604', gstRate: 18, description: 'Hand sieves' },
  { hsnCode: '9605', gstRate: 18, description: 'Travel sets toilet' },
  { hsnCode: '9606', gstRate: 18, description: 'Buttons, press-fasteners' },
  { hsnCode: '9607', gstRate: 18, description: 'Slide fasteners' },
  { hsnCode: '9608', gstRate: 18, description: 'Pens, markers' },
  { hsnCode: '9609', gstRate: 18, description: 'Pencils, crayons' },
  { hsnCode: '9610', gstRate: 18, description: 'Slates, boards' },
  { hsnCode: '9611', gstRate: 18, description: 'Date, sealing stamps' },
  { hsnCode: '9612', gstRate: 18, description: 'Ribbons inked' },
  { hsnCode: '9613', gstRate: 18, description: 'Cigarette lighters' },
  { hsnCode: '9614', gstRate: 18, description: 'Smoking pipes' },
  { hsnCode: '9615', gstRate: 18, description: 'Combs, hair-slides' },
  { hsnCode: '9616', gstRate: 18, description: 'Sprays, powder puffs' },
  { hsnCode: '9617', gstRate: 18, description: 'Vacuum flasks' },
  { hsnCode: '9618', gstRate: 18, description: 'Tailors dummies' },
  { hsnCode: '9619', gstRate: 12, description: 'Sanitary towels, diapers' },
  { hsnCode: '9620', gstRate: 18, description: 'Monopods, tripods' },
  { hsnCode: '9701', gstRate: 12, description: 'Paintings, drawings' },
  { hsnCode: '9702', gstRate: 12, description: 'Original engravings' },
  { hsnCode: '9703', gstRate: 12, description: 'Original sculptures' },
  { hsnCode: '9704', gstRate: 12, description: 'Postage stamps' },
  { hsnCode: '9705', gstRate: 12, description: 'Collections, specimens' },
  { hsnCode: '9706', gstRate: 12, description: 'Antiques >100 years' },
  { hsnCode: '9801', gstRate: 0, description: 'Project imports' },
  { hsnCode: '9802', gstRate: 0, description: 'Laboratory chemicals' },
  { hsnCode: '9803', gstRate: 0, description: 'Passenger baggage' },
  { hsnCode: '9804', gstRate: 0, description: 'Personal effects' },
  { hsnCode: '9805', gstRate: 0, description: 'Tourist purchases' },
  { hsnCode: '9961', gstRate: 5, description: 'SAC — Services by restaurants' },
  { hsnCode: '9962', gstRate: 5, description: 'SAC — Accommodation services' },
  { hsnCode: '9963', gstRate: 18, description: 'SAC — Restaurant with bar' },
  { hsnCode: '9965', gstRate: 18, description: 'SAC — Goods transport agency' },
  { hsnCode: '9966', gstRate: 18, description: 'SAC — Rental services' },
  { hsnCode: '9967', gstRate: 18, description: 'SAC — Support services' },
  { hsnCode: '9968', gstRate: 18, description: 'SAC — Maintenance services' },
  { hsnCode: '9969', gstRate: 18, description: 'SAC — Other services' },
  { hsnCode: '9971', gstRate: 18, description: 'SAC — Financial services' },
  { hsnCode: '9972', gstRate: 18, description: 'SAC — Real estate services' },
  { hsnCode: '9973', gstRate: 18, description: 'SAC — Leasing services' },
  { hsnCode: '9983', gstRate: 18, description: 'SAC — IT consulting' },
  { hsnCode: '9984', gstRate: 18, description: 'SAC — Telecom services' },
  { hsnCode: '9985', gstRate: 18, description: 'SAC — Support IT' },
  { hsnCode: '9986', gstRate: 18, description: 'SAC — Professional services' },
  { hsnCode: '9987', gstRate: 18, description: 'SAC — Maintenance IT' },
  { hsnCode: '9988', gstRate: 18, description: 'SAC — Other IT' },
  { hsnCode: '9989', gstRate: 18, description: 'SAC — Other miscellaneous' },
  { hsnCode: '9991', gstRate: 18, description: 'SAC — Public administration' },
  { hsnCode: '9992', gstRate: 18, description: 'SAC — Education services' },
  { hsnCode: '9993', gstRate: 18, description: 'SAC — Human health' },
  { hsnCode: '9994', gstRate: 18, description: 'SAC — Sewage, sanitation' },
  { hsnCode: '9995', gstRate: 18, description: 'SAC — Membership org' },
  { hsnCode: '9996', gstRate: 18, description: 'SAC — Recreational' },
  { hsnCode: '9997', gstRate: 18, description: 'SAC — Personal services' },
  { hsnCode: '9998', gstRate: 18, description: 'SAC — Domestic services' },
  { hsnCode: '9999', gstRate: 18, description: 'SAC — Services NEC' },
];

/**
 * @param {Array} apiConfigs from GET /api/gst/configurations
 * @param {Array} items from inventory
 * @returns {{ hsnCode: string, gstRate: number, description: string }[]}
 */
export function mergeHsnMaster(apiConfigs = [], items = []) {
  const byCode = new Map();
  const put = (code, gstRate, description) => {
    const k = String(code || '').trim();
    if (!k) return;
    const g = Number(gstRate);
    const rate = Number.isFinite(g) ? g : 18;
    if (!byCode.has(k)) byCode.set(k, { hsnCode: k, gstRate: rate, description: description || '' });
  };

  COMMON_HSN_REFERENCE.forEach((x) => put(x.hsnCode, x.gstRate, x.description));

  (apiConfigs || []).forEach((c) => {
    if (c && c.active === false) return;
    const code = (c.hsnCode || c.sacCode || '').toString().trim();
    if (code) put(code, c.gstRate, c.description);
  });

  (items || []).forEach((it) => {
    const code = (it.hsnCode || '').toString().trim();
    if (code) put(code, it.gstRate, it.itemName);
  });

  return Array.from(byCode.values()).sort((a, b) =>
    a.hsnCode.localeCompare(b.hsnCode, undefined, { numeric: true })
  );
}

export function gstRateForHsn(hsnMasterRows, code) {
  const k = String(code || '').trim();
  if (!k) return null;
  const row = hsnMasterRows.find((r) => r.hsnCode === k);
  return row ? row.gstRate : null;
}
